FROM registry.access.redhat.com/ubi9/openjdk-17:latest

USER root

RUN microdnf install -y git

RUN install -d /home/default/{{ SITE_NAME }}
COPY . /home/default/{{ SITE_NAME }}

RUN git clone https://github.com/computate-org/computate-base.git /home/default/computate-base
RUN git clone https://github.com/computate-org/computate-search.git /home/default/computate-search
RUN git clone https://github.com/computate-org/computate-vertx.git /home/default/computate-vertx
RUN git clone https://github.com/{{ GITHUB_ORG }}/{{ SITE_STATIC_NAME }}.git /home/default/{{ SITE_STATIC_NAME }}

WORKDIR /home/default/computate-base
RUN mvn clean install -DskipTests
WORKDIR /home/default/computate-search
RUN mvn clean install -DskipTests
WORKDIR /home/default/computate-vertx
RUN mvn clean install -DskipTests
WORKDIR $HOME/{{ SITE_NAME }}
RUN mvn clean install -DskipTests

WORKDIR /home/default/{{ SITE_NAME }}
RUN mvn clean install -DskipTests
RUN mvn dependency:build-classpath -Dmdep.outputFile=/home/default/{{ SITE_NAME }}/cp.txt -q
CMD java -cp "$(cat /home/default/{{ SITE_NAME }}/cp.txt):/home/default/{{ SITE_NAME }}/target/classes" {{ JAVA_MAIN_CLASS }}
