apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: postgres
spec:
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 5Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      replicas: 1
      name: 'postgres'
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.1-3.3-0
  postgresVersion: 15
  openshift: true
  postGISVersion: 3.3.0
  users:
    - name: keycloak
      options: "SUPERUSER"
      databases:
        - keycloak
    - name: "{{ DATABASE_USERNAME }}"
      options: "SUPERUSER"
      databases:
        - "{{ DATABASE_DATABASE }}"
  config:
    files:
      - configMap:
          name: {{ DATABASE_DATABASE }}-db-create
          items:
            - key: db-create.sql
              path: {{ DATABASE_DATABASE }}-db-create/db-create.sql
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host keycloak keycloak all md5"
          - "local keycloak keycloak trust"
          - "host {{ DATABASE_DATABASE }} {{ DATABASE_USERNAME }} all md5"
          - "local {{ DATABASE_DATABASE }} {{ DATABASE_USERNAME }} trust"
